### ISSUE TITLE
ZeroDay scene fails to launch "vkWaitForFences returned -4" (Vulkan/Linux) 

### ISSUE THREAD

**Issue by thesmallcreeper** [NVIDIAGameWorks/NRDSample#5]
ZeroDay scene fails to launch on Vulkan/Linux with the following error:
`[nri(VULKAN)::ERROR] -- Can't wait on a device semaphore: vkWaitForFences returned -4.`

Interestingly when enabling layers using `vkconfig` just before crashing the following validation error appear:
```VUID-VkBufferImageCopy-bufferRowLength-00195(ERROR` / SPEC): msgNum: -1083541747 - Validation Error: [ VUID-VkBufferImageCopy-bufferRowLength-00195 ] Object 0: handle = 0xaf8cd30000002cef, name =  (PD0), type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xbf6a770d | vkCmdCopyBufferToImage: pRegion[0] bufferRowLength (60) must be zero or greater-than-or-equal-to imageExtent.width (61). The Vulkan spec states: bufferRowLength must be 0, or greater than or equal to the width member of imageExtent (https://vulkan.lunarg.com/doc/view/1.3.211.0/linux/1.3-extensions/vkspec.html#VUID-VkBufferImageCopy-bufferRowLength-00195)```

The error occurs when `UploadTextures` of `UploadStaticData`.
From my investigation there might be bug with alignment of staging buffer. Might happen also on other platforms but crash out linux drivers. Haven't tried on Windows but it is possible by enabling validation layers this error is reported.

Can run the other examples just fine (with some tweaking for Linux environment) so I am fine for now, so I will study the other scenes. Thank you for providing such well-made samples.

**Comment by dzhdanNV** [comment]
@thesmallcreeper Many thanks and apologies for the delay! Debugged and fixed. As it turned out, the issue was on the texture loader side, but only mighty Vulkan validation managed to detect the problem. The fix is simple:
![image](https://user-images.githubusercontent.com/66380240/169018907-acdde581-61b3-4d72-9e5d-e40bc69f9183.png)

**Comment by dzhdanNV** [comment]
As it turned out, Zero Day scene has invalid "0-length" normals in some vertices. Now the object loader handles it as well. All these fixes will be uploaded on GitHub alongside with a new NRD release coming very soon (a few days).

As a teaser, I can say that AssImp will be replaced with a GLTF loader soon, opening a door to much more content.

**Comment by dzhdanNV** [comment]
As a side note, applying "the fix" in utils.h solves VK issue, but introduces a validation error in D3D12. Now it's fixed on the NRI-D3D12 side (will be updated soon).

**Comment by thesmallcreeper** [comment]
@dzhdanNV Thank you for the response! Feel free to close the issue whenever you want.

**Comment by dzhdanNV** [comment]
Fixed in v3.2.3 release. Thanks for the report @thesmallcreeper!

**Comment by thesmallcreeper** [comment]
@dzhdanNV Thank you for new release and specially for providing probabilistic selection of diffuse/selection. It has like a gift, you saved me from some work :smiley: :heart:
